services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=workouttrackerdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_LISTEN_PORT: '80'
    ports:
      - '15432:80'
    depends_on:
      - 'postgres'


